### ISSUE TITLE
It says a podcast is downloaded but I can't find it on disk? Also not playing anything for me…

### ISSUE THREAD

**Issue by ahmedelgabri** [jeff-hughes/shellcaster#22]
I'm trying Planet Money podcast from NPR & this is the feed URL https://feeds.npr.org/510289/podcast.xml

You can see that I have two downloaded episodes

<img width="1758" alt="Screenshot 2020-10-07 at 11 36 41" src="https://user-images.githubusercontent.com/63876/95314418-90598c80-0891-11eb-90cf-ff38145f3122.png">

When I try to play it says "Error: Could not play file. Check configuration." & here is my configuration. But I'm also trying to locate the episode on disk to test the `mpv %s` command _which should work_ ~but if I do `ls $XDG_DATA_HOME/` there is no shellcaster folder there…~ I found it under `~/Library/Application Support/shellcaster`, which makes me wonder why it's not respecting my config?

```toml
# Shellcaster settings
# --------------------

# Specifies where podcast episodes that are downloaded will be stored.
# Defaults:
# $XDG_DATA_HOME/shellcaster/ or $HOME/.local/share/shellcaster/ on Linux
# $HOME/Library/Application Support/shellcaster/ on Mac
# C:\Users\<User>\AppData\Local\shellcaster\ on Windows

download_path = "/Users/ahmed/.local/share/shellcaster/"


# Command to use to play episodes. Use "%s" to indicate where file/URL
# will be entered to the command.
# Default: vlc %s

play_command = "mpv %s"


# Maximum number of files to download simultaneously. Setting this too
# high could result in network requests being denied. A good general
# guide would be to set this to the number of processor cores on your
# computer.
# Default: 3

#simultaneous_downloads = 3


# Maximum number of times to retry connecting to a URL to sync a
# podcast or download an episode.
# Default: 3

#max_retries = 3


[keybindings]

# Keybindings must be an array of one or more strings.
# If you want to distinguish between a regular alphanumeric key
# and Shift+key, you can use the capital letter that you would normally
# type when pressing Shift+key (e.g., Shift+"r" will give you "R").

# Other special characters and their config string:
# Arrow keys: "Left", "Right", "Up", "Down"
# Ctrl+key: "C-key" (e.g., "C-r" means Ctrl+"r")
# Shift+key: "S-key" (e.g., "S-Del" means Shift+Delete)
# Insert ("Ins"), Delete ("Del"), Home ("Home"), End ("End"),
# Page up ("PgUp"), Page down ("PgDn"), Tab ("Tab")
# Enter ("Enter"), Escape ("Esc") -- be aware that on some terminals the
# Escape key waits for further input before passing it along to
# shellcaster, so you might notice a delay with this key

# Don't try to use backslash, or you're gonna have a bad time

left = [ "Left", "h" ]
right = [ "Right", "l" ]
up = [ "Up", "k" ]
down = [ "Down", "j" ]

add_feed = [ "a" ]
sync = [ "s" ]
sync_all = [ "S" ]

play = [ "Enter", "p" ]
mark_played = [ "m" ]
mark_all_played = [ "M" ]

download = [ "d" ]
download_all = [ "D" ]
delete = [ "x" ]
delete_all = [ "X" ]
remove = [ "r" ]
remove_all = [ "R" ]

quit = [ "q" ]
```
